### ISSUE TITLE
Sry guys but your paper is not worth more than zero :)

### ISSUE THREAD

**Issue by AmorfEvo** [majumderb/rezero#11]
The thing is I see 1 genius man, Jürgen Schmidhuber, who invented Highway Networks in May 2015, and here are his works and subsequent works which you failed to cite:

**Highway Networks** (2015 May & Nov v2)
https://arxiv.org/abs/1505.00387

**Training Very Deep Networks** (2015 Jul & Nov v2)
https://arxiv.org/pdf/1507.06228.pdf

And ResNet is only a special case of HighwayNet, when the 2 gates are constant 1.
**Highway and Residual Networks learn Unrolled Iterative Estimation** (2016 Dec & 2017 Mar v2&v3)
https://arxiv.org/abs/1612.07771

And here instead of using a gate tensor as in HighwayNet they just use a scalar multiplier like you, 
but in 2016, not in 2020... your scientific lagg is (significantly) more than zero.
**Learning Identity Mappings with Residual Gates** (2016 Nov & Dec v2)
https://arxiv.org/pdf/1611.01260v2.pdf

You did not cite either the Gated ResNet (which actually cite the HighwayNet) from 2016, neither the HighwayNet from 2015, but you cite the Kaiming He's ResNet (which also cite the HighwayNet).

**Comment by tbachlechner** [comment]
Dear AmorfEvo,

thank you for your constructive comments and references! We're currently revising our manuscript, including reviews and comparisons of prior work that use more complex gating mechanisms that we unfortunately missed to reference in our preprint submission.

It appears that Gated ResNet architecture contains the gate

``` y = (1 - a) * x + a * F(x) ```,

while Highway Networks are

```  
T = W_T * x + b_T 
y = T * F(x) + (1 - T) * x ,
```

with b_T initialized to be negative. You mention that the carry gate = 1 is an option in Highway Networks, but I see no canonical implementation we could compare to. 

We will be sure to directly compare both of these architectures to ReZero and give appropriate credit.
