### ISSUE TITLE
does rezero work in machine translation tasks?

### ISSUE THREAD

**Issue by zherowolf** [majumderb/rezero#5]
hi, guys,
did you have experiments in machine translation tasks? e.g. WMT ende or enfr
I experimented with rezero in my machine translation task,  while training with fp16, using rezero brings loss scale reaching minimum , with/without layernorm, does that make sense？

**Comment by majumderb** [comment]
Hi, thanks for your query. While we haven't tried with translation tasks, but we expect similar speed gains in enc-dec architecture as well. Let us if you find anything interesting.

**Comment by jiezhangGt** [comment]
> hi, guys,
> did you have experiments in machine translation tasks? e.g. WMT ende or enfr
> I experimented with rezero in my machine translation task, while training with fp16, using rezero brings loss scale reaching minimum , with/without layernorm, does that make sense？

Hi，do you train by fairseq? (tai zong)

**Comment by Mlair77** [comment]
> hi, guys,
> did you have experiments in machine translation tasks? e.g. WMT ende or enfr
> I experimented with rezero in my machine translation task, while training with fp16, using rezero brings loss scale reaching minimum , with/without layernorm, does that make sense？

I'm alse very interesting in its apply in NMT. does Rezero have improvements on WMT dataset?
